### ISSUE TITLE
iOS tasks require Java 9

### ISSUE THREAD

**Issue by jperedadnr** [javafxports/javafxmobile-plugin#11]
So far, iOS tasks require Java 9, and there is no check of the JDK used to run those tasks on the developer's machine.

In case the user has Java 8, after a long time of deployment, it will fail if JavaFX 8 API (com.sun.javafx.css....) is used.

This could be prevented if a check is done upfront, to warn the user about the required JDK

**Comment by tiainen** [comment]
Since Java 9 is absolutely required for iOS builds, but works just as well for android, I've decided to make Java 9 a requirement for all build tasks.

**Comment by jperedadnr** [comment]
That might be too restrictive. For instance using Java 8 on your IDE, running the desktop tasks won't be possible anymore.
