### ISSUE TITLE
FontAwesomeFX 9.1.2 hangs GluonVM on iOS

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#30]
org.javafxports:jfxmobile-plugin:2.0.8
FontAwesomeFX : 9.1.2
Platform : iOS (at least)

**Description**
FontAwesome hangs Gluon apps in iOS without any exception thrown.

**To Reproduce**
Take any working test project, add the following dependencies to build.gradle
The jars are in bintray (jcenter) [](https://bintray.com/jerady/maven/FontAwesomeFX/view)
```
    compile 'de.jensd:fontawesomefx-commons:9.1.2'
    compile 'de.jensd:fontawesomefx-controls:9.1.2'
    compile 'de.jensd:fontawesomefx-emojione:3.1.1-9.1.2'
    compile 'de.jensd:fontawesomefx-fontawesome:4.7.0-9.1.2'
    compile 'de.jensd:fontawesomefx-icons525:4.2.0-9.1.2'
    compile 'de.jensd:fontawesomefx-materialdesignfont:2.0.26-9.1.2'
    compile 'de.jensd:fontawesomefx-materialicons:2.2.0-9.1.2'
    compile 'de.jensd:fontawesomefx-materialstackicons:2.1-5-9.1.2'
    compile 'de.jensd:fontawesomefx-octicons:4.3.0-9.1.2'
    compile 'de.jensd:fontawesomefx-weathericons:2.0.10-9.1.2'
```
Add the following code:
```
try {
    System.out.println("Before");
    new FontAwesomeIconView(FontAwesomeIcon.SIGN_OUT);
} catch(Throwable t) {
    t.printStackTrace();
}
System.out.println("After");
```
The application will hang

**Comment by odbuser2** [comment]
org.javafxports:jfxmobile-plugin:2.0.12

Same behavior.  No exception or log message, just a hang.  Can you take a look?  Fontawesomefx is a very necessary library to use on Mobile.

**Comment by odbuser2** [comment]
**Workaround**
Depend on de.jensd:fontawesomefx-commons:9.1.2 but embed de.jensd:fontawesomefx-fontawesome:4.7.0-9.1.2 without the module-info.java file.

I haven't tracked down why this is the case.  It does NOT work if you recompile de.jensd:fontawesomefx-fontawesome:4.7.0-9.1.2 as a jar and depend on it - only if you embed the java and resources in the project...

**Comment by tiainen** [comment]
There was an issue that resource files from jar dependencies weren't included in three iOS app. That should be fixed now, so could you try again with the latest version 2.0.16?

**Comment by odbuser2** [comment]
Fixed.  Closing.  Thank you!
