### ISSUE TITLE
Class.forName(null) crashes app even when surrounded by try catch

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#40]
org.javafxports:jfxmobile-plugin:2.0.16
iOS:latest

The following will crash iOS but not desktop.

```
try {
Class.forName(null);
} catch (Throwable t) {
}
```
Of course this code shouldn't be written but unfortunately has been in third party libraries (E.g. when iterating items that may have a null value).

**Comment by johanvos** [comment]
Can you attach the logfile?
It seems to work for me:

[SUB] java.lang.NullPointerException
[SUB] 	at java.lang.Throwable.fillInStackTrace(Unknown Source)
[SUB] 	at java.lang.Throwable.<init>(Unknown Source)
[SUB] 	at java.lang.Exception.<init>(Unknown Source)
[SUB] 	at java.lang.RuntimeException.<init>(Unknown Source)
[SUB] 	at java.lang.NullPointerException.<init>(Unknown Source)
[SUB] 	at java.lang.Class.forName0(Unknown Source)
[SUB] 	at java.lang.Class.forName(Unknown Source)
[SUB] 	at com.gluonapplication2018.GluonApplication2018.init(Unknown Source)
[SUB] 	at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
[SUB] 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
[SUB] 	at com.sun.javafx.application.LauncherImpl$$Lambda$2.run(Unknown Source)
[SUB] 	at java.lang.Thread.run(Unknown Source)

**Comment by odbuser2** [comment]
Tried again and can't reproduce.  Closing.
