### ISSUE TITLE
libimobiledevice library gpl 2.0?

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#43]
According to the following web page it's LGPL 2.1

http://www.libimobiledevice.org/
"This library is free open source software and licensed under the LGPL 2.1."

but a recent update to javafxmobile-plugin/NOTICE.txt it says GPL 2.0... this has some serious implications:

"This project uses libimobiledevice:
https://github.com/libimobiledevice/libimobiledevice
which is copyrighted under the GPL v2.0 license"

**Comment by johanvos** [comment]
If I understand it correctly, libimobiledevice has 2 licenses: 
GPL 2.0 https://github.com/libimobiledevice/libimobiledevice/blob/master/COPYING
and
LGPL 2.1 https://github.com/libimobiledevice/libimobiledevice/blob/master/COPYING.LESSER

Unless I'm missing something?

The goal is to ultimately build everything fully automated from source but that will take more time.

**Comment by odbuser2** [comment]
Yes I agree.  You might want to change  javafxmobile-plugin/NOTICE.txt to reference LGPL 2.1 instead of GPL 2.0.

**Comment by johanvos** [comment]
Done.
