### ISSUE TITLE
OrientationService fails and hangs app on iOS

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#45]
org.javafxports:jfxmobile-plugin:2.0.18
iOS latest
downconfig 3.7.0

**Description**
OrientationService fails and hangs the application with the following:
```
EXCEPtion in clinit for class com/gluonhq/charm/down/plugins/ios/IOSOrientationService: 0x1105a49b0
Exception in Application start method
QuantumRenderer: shutdown
DONE DONE DONE
[JVDBG] VM started
```

**To Reproduce**
Use any basic gluon app and add the following:
```
        Services.get(OrientationService.class).ifPresent(t -> {
            System.out.println("Hello");
        });
```

**Comment by jperedadnr** [comment]
Bump Charm Down to 3.7.2 and try again.

(Note that the IDE plugin already provides jfxmobile 2.0.18 with Down 3.7.2 if you create a new project, but I guess you were modifying an existing project)

**Comment by odbuser2** [comment]
Yes that fixed it.  Copy and paste error on my part.  Closing.
