### ISSUE TITLE
iOS Assets: allow inner folders

### ISSUE THREAD

**Issue by jperedadnr** [javafxports/javafxmobile-plugin#49]
iOS 11 requires an AppIcon folder within the assets folder.

**Comment by johanvos** [comment]
I think this is fixed now?

**Comment by jperedadnr** [comment]
There is a pending PR for GluonTools, and then a follow-up PR is required here

**Comment by johanvos** [comment]
com.gluonhq:gvmbuilder:0.0.25 is released
