### ISSUE TITLE
androidInstall : default or static interface method used without --min-sdk-version >= 24

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#50]
org.javafxports:jfxmobile-plugin:2.0.19
controlfx 9.0.0 branch
gradle target: androidInstall

**Description**
ControlFX does not build properly using AndroidInstall : "default or static interface method used without --min-sdk-version >= 24".  However, this is what's in AndroidManifest.xml

`<uses-sdk android:minSdkVersion="24" android:targetSdkVersion="25"/>`

Specifying the minSdkVersion=24 in the build.gradle file results in the same error.

I haven't tracked down the source of the issue in ControlFX but I did try default and static interface methods in my source.  Default methods work fine.  static interface methods compile but fail to launch on Android.  The issue with ControlFX has some other nuance.

The following appears to be the same issue:
[Stackoverflow question](https://stackoverflow.com/questions/46754337/default-or-static-interface-method-used-without-min-sdk-version-24)
Trying "android.enableD8=true" in the gradle.properties file did not fix the issue.

**Error**
```
00:02  INFO: Saving lambda class: impl/org/controlsfx/skin/HiddenSidesPaneSkin$$Lambda$6
00:02  INFO: Saving lambda class: impl/org/controlsfx/skin/HiddenSidesPaneSkin$$Lambda$7
00:02  INFO: Saving lambda class: org/controlsfx/control/textfield/TextFields$$Lambda$1
:App:mergeClassesIntoJar
:App:shrinkMultiDexComponents
:App:createMainDexList
:App:writeInputListFile
[ant:java] Java Result: 1
:App:dex FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':App:dex'.
> Uncaught translation error: com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
  1 error; aborting
```

**Comment by kermiedefrog** [comment]
Did you resolve this issue >>> I am having the same issue with the ControlFX code too ...

**Comment by JulienSt** [comment]
@jperedadnr Thank you so much, I had the same problem with a different library. After 2weeks of searching the web I finaly found this github post.
@kermiedefrog yes, this seems to be resolving the problem
