### ISSUE TITLE
Oracle Java9 is out of support and not available on oracle.com.  Plugin fix needed.

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#52]
org.javafxports:jfxmobile-plugin:2.0.19

Java9 is no longer supported by Oracle and wide support for OpenJDK 9 is not available.  Will OpenJDK 10.0.1 or Oracle JDK 10.0.1 by the plugin?

Everything appears to work fine with the latest Oracle JDK 10.0.1 but you have to change one line in the plugin for it to work:

src/main/groovy/org/javafxports/jfxmobile/plugin/JFXMobilePlugin.groovy

From:
`125        if (JavaVersion.current() != JavaVersion.VERSION_1_9) {`
To:
`125        if (!JavaVersion.current().isJava9Compatible()) {`

recompile the plugin and depend on that version.

**Comment by johanvos** [comment]
Thanks, you're right about the hard dependency on 9 that should be removed.
We're working on Java 11 right now, as that will be an LTS and it will be released relative soon, with beta's already out.

**Comment by odbuser2** [comment]
Can you release 2.0.20 with this fix?

**Comment by johanvos** [comment]
released (with a bunch of other fixes)

**Comment by odbuser2** [comment]
Verified.  Thank you.
