### ISSUE TITLE
createIosApp uses dev profile only

### ISSUE THREAD

**Issue by kermiedefrog** [javafxports/javafxmobile-plugin#63]
have set iosSignIdentity and iosProvisioningProfile to the correct data but the build will only select my dev profile ... 
Where are the options to set it for a production build and use my Distribution Profile

**Comment by jperedadnr** [comment]
It should be fixed since 2.0.25
@kermiedefrog if you can try and verify it works for you, we can close this issue.

**Comment by jperedadnr** [comment]
2.0.30 contains a fix that checks if the provisioning profile is for development before setting the entitlements.
