### ISSUE TITLE
Depends on an ancient Gradle version

### ISSUE THREAD

**Issue by zilti** [javafxports/javafxmobile-plugin#76]
jfxmobile-plugin 1.3.11 depends via `com.android.application` on Gradle 2.2, which makes it pretty much unusable with most plugins. The dependency on `com.android.application` should be updated to something usable.

`Gradle version 2.2 is required. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl`

**Comment by tiainen** [comment]
The jfxmobile plugin requires gradle 4.2 at its minimum. See https://github.com/javafxports/javafxmobile-plugin/blob/1534107429a184910d3728d15a44a39a475a832c/src/main/groovy/org/javafxports/jfxmobile/plugin/JFXMobilePlugin.groovy#L121

The line that you pasted must come from another plugin. Note that you won't be able to apply both the jfxmobile plugin and the official Android gradle plugin.

**Comment by zilti** [comment]
Hmm, must have been... I created a blank project with gradle-clojure, added the javafxports stuff, and mysteriously, it works now :)
