### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by piosystems** [javafxports/javafxmobile-plugin#87]
This project has not been updated for a long time despite the fact that it is not up-to-date with recent JVM versions. Is the project dead?

**Comment by tiainen** [comment]
The project itself is not dead, it has merely been superseded by the [Gluon Substrate project](https://github.com/gluonhq/substrate), which works on Java 11 and later and has a better overall approach for supporting multiple platforms.

The javafxmobile project can only be used with projects that have not yet migrated away from Java 8.
