### ISSUE TITLE
Adding other modules to gvm

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#9]
Modules such as java.management do not appear to be present in gvm.  Is there a way to add modules to the build from the standard JDK as well as other ones?

Adding modules using --add-modules in the build.gradle leads to more problems:

> option --add-modules not allowed with target 1.8
Resolved by commenting out sourceCompatibility and targetCompatibility lines.

That leads to (I think) split module issues with charm libraries.  I stopped here.

**Comment by johanvos** [comment]
Good comment. At this moment, the java.management module is not yet available on mobile, but that should be fixed soon, as it is already built by OpenJDK Mobile.

**Comment by odbuser2** [comment]
OpenJDK Mobile page says "Support at minimum the equivalent of JDK 8 compact2 profile (in module form)"
http://openjdk.java.net/projects/mobile/

But it's compact3 that supports java.management.  Is there a comprehensive list of modules supported by OpenJDK Mobile 9 or more importantly with GVM?

Even compact3 may not be enough...  Without this information up front, users are going to assume that OpenJDK (Full SE) is supported by GVM.

**Comment by johanvos** [comment]
In theory, there is no reason why the full SE can't be supported. 
If the modules only contain Java files, they should run out of the box on Gluon VM (well, not entirely, as for now we require them to be compiled with  -XDstringConcat=inline but we have to fix that.
If there is native code involved as well, this has to be compiled for ios-arm.
Also, we should allow developers to indicate which modules they need, or even better get them from the dependency chain automatically. 
I'll create new issues for this.
Meanwhile, the latest build of Gluon VM includes the javax.management module so this issue can probably be closed after the new issues have been created.

**Comment by odbuser2** [comment]
I've confirmed that javax.management is included in org.javafxports:jfxmobile-plugin:2.0.1 on iOS.  However, I ran into a similar issue with java.lang.management.ManagementFactory on Android.

**Comment by johanvos** [comment]
Can you provide a code snippet that allows us to reproduce it?

**Comment by odbuser2** [comment]
org.javafxports:jfxmobile-plugin:2.0.1

On OSX and iOS, the javax.management.Attribute class is found.  On Android it is not found.  Modify the singleview-gluonvmApp with the following and press the button to lookup the class.

```java
public BasicView(String name) {
        super(name);

        Label label = new Label("Hello JavaFX World!");

        TextField textField = new TextField("javax.management.Attribute");
        Button button = new Button("Change the World!");
        button.setGraphic(new Icon(MaterialDesignIcon.LANGUAGE));
        button.setOnAction(event -> {
            String numbers = IntStream.range(1, 11).boxed().map(String::valueOf).collect(Collectors.joining(", "));
            label.setText(numbers);
            try {
                Class<?> c = Class.forName(textField.getText());
                label.setText(textField.getText() + " FOUND");
            } catch(Exception e) {
                label.setText(textField.getText() + " NOT FOUND");
            }
        });
        VBox controls = new VBox(15.0, label,textField, button);
        controls.setAlignment(Pos.CENTER);

        setCenter(controls);
    }
```

**Comment by odbuser2** [comment]
Can you include everything that **java.se** depends on?  The next two that I'll need are:
java.naming
java.scripting

I know that java.desktop is filled with awt, but there are a lot of libraries (graphic based) that rely on awt and imageio classes (not necessarily native code) that would require a lot of rework to run under gluon.

**java.se**
java.compiler
java.datatransfer
java.desktop
java.instrument
java.logging
java.management
java.management.rmi
java.naming
java.prefs
java.rmi
java.scripting
java.security.jgss
java.security.sasl
java.sql
java.sql.rowset
java.xml
java.xml.crypto

**Comment by johanvos** [comment]
We don't use Gluon VM on Android at the moment, so we rely on the JDK-8'ish classpath there. We provide some workarounds though -- can you create separate issues for the Android deps?

The following modules will be in the upcoming Gluon VM release (probably tomorrow)
      ```
  "java.base",
        "java.logging",
        "java.xml",
        "java.sql",
        "java.security.jgss",
        "java.security.sasl",
        "java.management",
        "java.desktop",
        "java.datatransfer"
        "javafx.base",
        "javafx.graphics",
        "javafx.controls",
        "javafx.web",
        "javafx.fxml"
```
Yes, we have java.desktop :)

**Comment by odbuser2** [comment]
I will open separate issues for Android but I hope the either Gluon VM will be supported or the same set of packages equivalent to the modules being included in Gluon VM will be present on Android in the meantime.

I've confirmed that java.desktop is present in the latest version (2.0.5).  However, I'm unable to use libraries that depend on it (yet) due to missing vm classes which I'll document when I can narrow it down.  If you wanted to see, try depending on batik-all.  Ultimately, I don't think I actually need batik-all but due to split package issues with individual batik jars on Java9, batik-all is required.

javax.naming and scripting are still not present.  Graal ever becomes a reality, I suppose scripting will no longer be necessary.  naming is a very basic necessity for connecting with standard repositories for a variety of authentication systems.

**Comment by johanvos** [comment]
In the upcoming release, a property has been added that allows you to specify the modules you want to be available at runtime (in jfxmobile { ios {runtimeModules[]}})

If the modules you specify are supported in Gluon VM, they will be added to the classpath.

See https://github.com/javafxports/javafxmobile-plugin/commit/4486a76833355cc56bb6976819dfbfbe9d9f47f1

Note that we by default do not all the modules on the classpath, in order to keep the binary small. That means some methods references classes that are not on the classpath. The AOT ignores those classes, but if they are called at runtime they will of course give exceptions.
